[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  madhephaestus/ESP32Servo@^3.0.6
  adafruit/Adafruit Unified Sensor @ ^1.1.15
  adafruit/Adafruit BMP5xx Library @ ^1.0.2
  adafruit/Adafruit LSM6DS @ ^4.7.4
  adafruit/Adafruit BusIO @ ^1.16.1
  
